<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssessmentsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('assessments')->delete();

        DB::table('assessments')->insert([
            0 => [
                'id' => 1,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 1,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Reparación estimada de soporte cortina plástico en entrada a cámara',
                'unit_price' => '50.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:51:15',
                'updated_at' => '2021-11-11 18:51:15',
            ],
            1 => [
                'id' => 2,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 1,
                'currency_id' => 1,
                'unit' => '8.00',
                'deprecationgroup_id' => null,
                'description' => 'Mano de obra para desmontaje, reparación y montaje de puerta doble peatonal de acceso a la nave',
                'unit_price' => '41.40',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:51:37',
                'updated_at' => '2021-11-11 18:51:37',
            ],
            2 => [
                'id' => 3,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 1,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Material necesario para reparación in situ de puerta de paso con daños',
                'unit_price' => '240.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:51:52',
                'updated_at' => '2021-11-11 18:51:52',
            ],
            3 => [
                'id' => 4,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 1,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Repintado de puerta de dos hojas con esmalte por ambas caras (hasta 10 m²)',
                'unit_price' => '91.80',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:53:29',
                'updated_at' => '2021-11-11 18:53:29',
            ],
            4 => [
                'id' => 5,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 1,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Suministro e instalación de cerradura en puerta doble acceso peatonal',
                'unit_price' => '143.40',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:53:44',
                'updated_at' => '2021-11-11 18:53:44',
            ],
            5 => [
                'id' => 6,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 2,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Soldar puerta peatonal dejando el riesgo protegido, pendiente de reparación provisional',
                'unit_price' => '95.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:54:00',
                'updated_at' => '2021-11-11 18:54:00',
            ],
            6 => [
                'id' => 7,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 1,
                'subguarantee_id' => 8,
                'destiny_id' => 2,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Incremento por urgencia y fin de semana',
                'unit_price' => '45.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 18:54:14',
                'updated_at' => '2021-11-11 18:54:14',
            ],
            7 => [
                'id' => 8,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento A',
                'unit_price' => '17041.37',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:02:21',
                'updated_at' => '2021-11-11 19:02:21',
            ],
            8 => [
                'id' => 9,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento B',
                'unit_price' => '3251.34',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:02:45',
                'updated_at' => '2021-11-11 19:02:45',
            ],
            9 => [
                'id' => 10,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento C',
                'unit_price' => '16244.47',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:02:58',
                'updated_at' => '2021-11-11 19:02:58',
            ],
            10 => [
                'id' => 11,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento',
                'unit_price' => '1268.25',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:03:13',
                'updated_at' => '2021-11-11 19:03:13',
            ],
            11 => [
                'id' => 12,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento E',
                'unit_price' => '4051.23',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:03:46',
                'updated_at' => '2021-11-11 19:03:46',
            ],
            12 => [
                'id' => 13,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento F',
                'unit_price' => '348.13',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:10:21',
                'updated_at' => '2021-11-11 19:10:21',
            ],
            13 => [
                'id' => 14,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento G',
                'unit_price' => '964.39',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:10:38',
                'updated_at' => '2021-11-11 19:10:38',
            ],
            14 => [
                'id' => 15,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento H',
                'unit_price' => '8784.74',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:10:53',
                'updated_at' => '2021-11-11 19:10:53',
            ],
            15 => [
                'id' => 16,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento I',
                'unit_price' => '1777.50',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:11:06',
                'updated_at' => '2021-11-11 19:11:06',
            ],
            16 => [
                'id' => 17,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento J',
                'unit_price' => '1799.02',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:11:18',
                'updated_at' => '2021-11-11 19:11:18',
            ],
            17 => [
                'id' => 18,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento K',
                'unit_price' => '936.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:11:32',
                'updated_at' => '2021-11-11 19:11:32',
            ],
            18 => [
                'id' => 19,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento L',
                'unit_price' => '1396.40',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:11:42',
                'updated_at' => '2021-11-11 19:11:42',
            ],
            19 => [
                'id' => 20,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento M',
                'unit_price' => '990.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:11:54',
                'updated_at' => '2021-11-11 19:11:54',
            ],
            20 => [
                'id' => 21,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género robado y acreditado según documento adjunto Analisis coste productos, y acreditados con el documento N',
                'unit_price' => '9473.36',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:12:06',
                'updated_at' => '2021-11-11 19:12:06',
            ],
            21 => [
                'id' => 22,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 10,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Género sin acreditar (línea 35)',
                'unit_price' => '564.48',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:12:18',
                'updated_at' => '2021-11-11 19:12:18',
            ],
            22 => [
                'id' => 23,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 13,
                'subguarantee_id' => 9,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Reposición de ordenador, monitor y tarjeta para cámaras de vigilancia',
                'unit_price' => '575.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:13:05',
                'updated_at' => '2021-11-11 19:13:05',
            ],
            23 => [
                'id' => 24,
                'expedient_id' => 1,
                'person_id' => 1,
                'capital_id' => 13,
                'subguarantee_id' => 10,
                'destiny_id' => 3,
                'currency_id' => 1,
                'unit' => '1.00',
                'deprecationgroup_id' => null,
                'description' => 'Dinero en efectivo robado (2.024,44 €) limitados según condiciones particulares',
                'unit_price' => '1500.00',
                'taxes' => null,
                'deprecation' => null,
                'origin' => null,
                'created_at' => '2021-11-11 19:13:33',
                'updated_at' => '2021-11-11 19:13:33',
            ],
        ]);
    }
}
