<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypecasesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('typecases')->delete();

        DB::table('typecases')->insert([
            0 => [
                'id' => 1,
                'ramo_id' => 1,
                'name' => 'generico',
                'texts' => null,
                'preexistences' => 1,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 18:08:57',
            ],
            1 => [
                'id' => 2,
                'ramo_id' => 1,
                'name' => 'incendio',
                'texts' => 'incendio',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            2 => [
                'id' => 3,
                'ramo_id' => 1,
                'name' => 'responsabilidad civil',
                'texts' => 'rc',
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            3 => [
                'id' => 4,
                'ramo_id' => 1,
                'name' => 'agua',
                'texts' => 'agua',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            4 => [
                'id' => 5,
                'ramo_id' => 2,
                'name' => 'generico',
                'texts' => null,
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            5 => [
                'id' => 6,
                'ramo_id' => 2,
                'name' => 'incendio',
                'texts' => 'incendio',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            6 => [
                'id' => 7,
                'ramo_id' => 2,
                'name' => 'responsabilidad civil',
                'texts' => 'rc',
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            7 => [
                'id' => 8,
                'ramo_id' => 2,
                'name' => 'agua',
                'texts' => 'agua',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            8 => [
                'id' => 9,
                'ramo_id' => 3,
                'name' => 'generico',
                'texts' => null,
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            9 => [
                'id' => 10,
                'ramo_id' => 3,
                'name' => 'incendio',
                'texts' => 'incendio',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            10 => [
                'id' => 11,
                'ramo_id' => 3,
                'name' => 'responsabilidad civil',
                'texts' => 'rc',
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            11 => [
                'id' => 12,
                'ramo_id' => 3,
                'name' => 'agua',
                'texts' => 'agua',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            12 => [
                'id' => 13,
                'ramo_id' => 4,
                'name' => 'generico',
                'texts' => null,
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            13 => [
                'id' => 14,
                'ramo_id' => 4,
                'name' => 'incendio',
                'texts' => 'incendio',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            14 => [
                'id' => 15,
                'ramo_id' => 4,
                'name' => 'responsabilidad civil',
                'texts' => 'rc',
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            15 => [
                'id' => 16,
                'ramo_id' => 4,
                'name' => 'agua',
                'texts' => 'agua',
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 14:58:41',
                'updated_at' => '2021-11-11 14:58:41',
            ],
            16 => [
                'id' => 17,
                'ramo_id' => 5,
                'name' => 'Incendio',
                'texts' => null,
                'preexistences' => 1,
                'tasacion' => 0,
                'created_at' => '2021-11-11 17:10:44',
                'updated_at' => '2021-11-11 17:12:11',
            ],
            17 => [
                'id' => 18,
                'ramo_id' => 5,
                'name' => 'Inundación',
                'texts' => null,
                'preexistences' => 1,
                'tasacion' => 0,
                'created_at' => '2021-11-11 17:11:51',
                'updated_at' => '2021-11-11 17:12:10',
            ],
            18 => [
                'id' => 19,
                'ramo_id' => 5,
                'name' => 'Responsabilidad Civil',
                'texts' => null,
                'preexistences' => 0,
                'tasacion' => 0,
                'created_at' => '2021-11-11 17:12:00',
                'updated_at' => '2021-11-11 17:12:00',
            ],
            19 => [
                'id' => 20,
                'ramo_id' => 1,
                'name' => 'robo',
                'texts' => null,
                'preexistences' => 1,
                'tasacion' => 1,
                'created_at' => '2021-11-11 18:47:59',
                'updated_at' => '2021-11-11 18:48:29',
            ],
        ]);
    }
}
